= Rest Docs Sample
bsw;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-request-fields-title: 요청 필드
:operation-path-parameters-title: 경로 변수
:operation-response-fields-title: 응답 필드
:operation-curl-request-title: 요청 예제
:operation-http-response-title: 응답 예제

[[overview]]
= 개요

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 |

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우.

| `403 Forbidden`
| 허용되지 않는 사용자 접근.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있습니다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따릅니다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 합니다.

[[resources]]
= 리소스

[[resources-common]]
== 공통 헤더

공통 헤더가 없으면 `403 Forbidden` 코드로 응답합니다.

|===
|헤더명|설명

|`+X-USER-ID+`
|사용자의 식별값

|===

[[books]]
== Book 단건 조회

bookId로 Book 단건 조회

operation::books/getOne[snippets='request-fields,response-fields,curl-request,http-response']

[[resources-money-pickup]]
== Put

`Put` 요청

operation::put[snippets='path-parameters,response-fields,curl-request,http-response']

[[resources-money-inquiry]]
== Get

`Get` 요청

operation::books/getOne[snippets='path-parameters,response-fields,curl-request,http-response']
